name: saidlity
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  carousel_slider: ^4.2.1
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  get_it: ^7.6.7
  lottie: ^3.0.0
  conditional_builder_null_safety: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/


 


  fonts:
    - family: DM_Sans
      fonts:
        - asset: assets/fonts/dm_sans/DMSans-Black.ttf
          style: normal
        - asset: assets/fonts/dm_sans/DMSans-BlackItalic.ttf
          style: italic
        - asset: assets/fonts/dm_sans/DMSans-Bold.ttf
          style: normal
        - asset: assets/fonts/dm_sans/DMSans-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/dm_sans/DMSans-ExtraBold.ttf
          style: normal
        - asset: assets/fonts/dm_sans/DMSans-ExtraBoldItalic.ttf
          style: italic
        - asset: assets/fonts/dm_sans/DMSans-ExtraLight.ttf
          style: normal
        - asset: assets/fonts/dm_sans/DMSans-ExtraLightItalic.ttf
          style: italic
        - asset: assets/fonts/dm_sans/DMSans-Italic.ttf
          style: italic
        - asset: assets/fonts/dm_sans/DMSans-Light.ttf
          style: normal
        - asset: assets/fonts/dm_sans/DMSans-LightItalic.ttf
          style: italic
        - asset: assets/fonts/dm_sans/DMSans-Medium.ttf
          style: normal
        - asset: assets/fonts/dm_sans/DMSans-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/dm_sans/DMSans-Regular.ttf
          style: normal
        - asset: assets/fonts/dm_sans/DMSans-SemiBold.ttf
          style: normal
        - asset: assets/fonts/dm_sans/DMSans-SemiBoldItalic.ttf
          style: italic
        - asset: assets/fonts/dm_sans/DMSans-Thin.ttf
          style: normal
        - asset: assets/fonts/dm_sans/DMSans-ThinItalic.ttf
          style: italic

